name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: soulshake
      COMMIT: ${{ github.sha }}
      REPO: front-end
      DOCKERHUB_USERNAME: soulshake
      DOCKERHUB_REPOSITORY: front-end
    steps:
    - uses: actions/checkout@v2

    #
    #
    # Set up  node
    - uses: actions/setup-node@v1
      with:
        node-version: '4.x'

    #
    #
    # Install dependencies
    - run: npm install

    #
    #
    # Run node tests in docker image
    - name: Test image
      env:
        DOCKER_BUILDKIT: 1
      run: make test

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    #
    #
    # Build docker image for service
    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}

    #
    #
    # Run simple test against built container
    - name: Test docker image
      env:
        DOCKER_BUILDKIT: 1
      run: ./test/container.sh

    #
    #
    # Push to dockerhub
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      if: true || startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
